import { ArrowUpRight } from "lucide-react";
import { CaseStudyLayout, DeepDive, Tags } from "./CaseStudyLayout";

const CookBridgeCaseStudy = () => <CaseStudyLayout><article className="case-study case-study-page__content">
  <div className="case-study-hero"><div className="project-visual"><img src="/images/cookbridge-project.jpg" alt="Indian home-cooked meal planning with a phone assistant" /><span>01</span></div><div className="project-story"><div className="project-meta"><span>Technical Product Manager / AI Product Builder</span><span>0→1 case study</span></div><h1>CookBridge</h1><p className="project-question">Taking “Aaj khane mein kya banega?” out of the household’s head.</p><Tags items={["0→1 Product", "User Research", "AI", "Prototype"]} /></div></div>
  <section className="case-moment"><p className="case-label">The problem</p><h2>Meal decisions carry more household work than they should.</h2><div className="evidence-row"><div><strong>7/10</strong><span>households experienced the problem</span></div></div></section>
  <section className="case-moment"><p className="case-label">The context</p><h2>A decision needs more than a recipe.</h2><p className="principle">Diet <b>+</b> Preferences <b>+</b> Recent meals <b>+</b> Available ingredients <b>→</b> Meal decision</p></section>
  <section className="case-moment"><p className="case-label">Prototype</p><h2>Make the decision, then make it cook-ready.</h2><p className="case-copy">I built an interactive prototype to test the intended household experience before committing more engineering effort.</p><a className="prototype-link prototype-link--inline" href="https://cookbridge-whats-for-tea.lovable.app" target="_blank" rel="noreferrer">Try prototype <ArrowUpRight size={16} /></a></section>
  <section className="case-moment decision-block--highlight"><p className="case-label">A failed assumption</p><h2>The inventory assumption broke.</h2><div className="assumption-flow"><p><span>Initial assumption</span>CookBridge can maintain accurate inventory.</p><b>→</b><p><span>Observed problem</span>Exact updates created another household chore.</p><b>→</b><p><span>Product decision</span>Inventory becomes a household belief.</p></div><p className="belief-flow">Available <b>→</b> Low <b>→</b> Probably Finished <b>→</b> Unknown</p></section>
  <section className="case-moment"><p className="case-label">Prototype testing</p><h2>45 sec is too long at the moment of decision.</h2><div className="latency-line"><strong>45 sec</strong><p>A cold-start response after inactivity turns a product meant to reduce interruption into a new wait.</p></div></section>
  <section className="case-moment"><p className="case-label">What changed / current direction</p><h2>Testing changed the product, not just the interface.</h2><div className="learning-lines"><p><span>WhatsApp-only flow</span><b>Setup was cumbersome</b><em>Web onboarding + WhatsApp usage</em></p><p><span>Exact inventory</span><b>Too much maintenance effort</b><em>Belief-based inventory</em></p><p><span>Selection treated as final</span><b>Selecting isn’t cooking</b><em>Selected / Rejected / Confirmed</em></p><p><span>One recommendation path</span><b>People start with different knowledge</b><em>Suggest Meals / I Have Ingredients</em></p></div><p className="case-copy"><strong>Only Confirmed</strong> updates meal history and inventory.</p></section>
  <div className="case-deep-dives"><DeepDive title="Research"><p>10 household conversations informed the work. The current self-test measures meal-decision time and whether someone still needs to check the fridge manually.</p></DeepDive><DeepDive title="Scope & trade-offs"><p>A working prototype makes the intended experience tangible; it does not prove repeated use. The next question is whether household context and meal history earn a return visit over time.</p></DeepDive><DeepDive title="What I would validate next"><p>Success metrics, instrumentation, technical risks and implementation-level detail remain available for a hiring-manager discussion rather than the recruiter path.</p></DeepDive></div>
</article></CaseStudyLayout>;

export default CookBridgeCaseStudy;
