import { CaseStudyLayout, DeepDive, Tags } from "./CaseStudyLayout";

const FashionStylistCaseStudy = () => <CaseStudyLayout><article className="case-study fashion-case case-study-page__content">
  <div className="case-study-hero"><div className="project-visual"><img src="/images/ai-fashion-stylist-project.jpg" alt="Personal wardrobe with three digital outfit suggestions" /><span>02</span></div><div className="project-story"><div className="project-meta"><span>AI Product Builder</span><span>Working prototype</span></div><h1>AI Fashion Stylist</h1><p className="project-question">Can AI style you without inventing clothes you don’t own?</p><Tags items={["AI Vision", "Structured Context", "WhatsApp", "Prototype"]} /></div></div>
  <section className="case-moment"><p className="case-label">Working demo</p><h2>See the wardrobe-grounded flow.</h2><div className="video-wrap"><video controls playsInline preload="metadata" poster="/images/ai_fashion_stylist_in_action.png" aria-label="AI Fashion Stylist prototype demo"><source src="/videos/ai-fashion-stylist-demo.mp4" type="video/mp4" />Your browser does not support the embedded AI Fashion Stylist demo video.</video></div></section>
  <section className="case-moment"><p className="case-label">How it works</p><h2>Structure the wardrobe before reasoning about outfits.</h2><p className="principle">Wardrobe photos <b>→</b> Vision extraction <b>→</b> Structured wardrobe <b>→</b> Outfit reasoning <b>→</b> WhatsApp recommendation</p></section>
  <section className="case-moment"><p className="case-label">AI constraint</p><h2>The hard part was grounding the AI.</h2><div className="grounding-compare"><p><span>Generic AI stylist</span>User asks for an outfit <b>→</b> attractive recommendation <b>→</b> may not own it</p><p><span>Wardrobe-grounded system</span>Known wardrobe <b>→</b> structured context <b>→</b> combinations from actual items</p></div></section>
  <section className="case-moment"><p className="case-label">Key decisions</p><h2>Three choices kept the prototype useful.</h2><div className="key-decisions"><p><strong>Ground the model first</strong> — extraction precedes generation.</p><p><strong>Structured context over raw images</strong> — a cleaner reasoning layer for known items.</p><p><strong>WhatsApp-first prototype</strong> — accessible without another app to install.</p></div></section>
  <div className="case-deep-dives"><DeepDive title="Research & next question"><p>I researched Acloset and Indyx, spoke with the Indyx founder, and studied how people organise wardrobes and decide what to wear. The next validation question is inference cost.</p></DeepDive></div>
</article></CaseStudyLayout>;

export default FashionStylistCaseStudy;
